- id: validate-legend-chmaps
  name: check LEGEND channel maps format
  entry: validate-legend-chmaps
  language: python
  types: [yaml]

- id: validate-legend-detdb
  name: check LEGEND detector database format
  entry: validate-legend-detdb
  language: python
  types: [yaml]

- id: validate-validity
  name: check LEGEND validity format
  entry: validate-validity
  language: python
  files: (.*\/)?validity\..+$
  types_or: [yaml, json]

- id: validate-dataflow-config
  name: check LEGEND dataflow config files
  entry: validate-dataflow-config
  language: python
  files: (.*\/)?validity\..+$
  types_or: [yaml, json]

- id: validate-statuses
  name: check LEGEND status files format
  entry: validate-statuses --fix
  language: python
  files: (.*\/)?validity\..+$
  types_or: [yaml, json]

- id: validate-cal-groupings
  name: check LEGEND calibration groupings format
  entry: validate-cal-groupings --fix
  language: python
  files: (.*\/)?cal_groupings\..+$
  types: [yaml]

- id: validate-phy-groupings
  name: check LEGEND physics groupings format
  entry: validate-phy-groupings --fix
  language: python
  files: (.*\/)?phy_groupings\..+$
  types: [yaml]
