- id: validate-legend-chmaps
  name: check LEGEND channel maps format
  entry: validate-legend-chmaps
  language: python
  types: [yaml]

- id: validate-legend-detdb
  name: check LEGEND detector database format
  entry: validate-legend-detdb
  language: python
  types: [yaml]

- id: validate-validity
  name: check LEGEND validity format
  entry: validate-validity
  language: python
  files: (.*\/)?validity\..+$
  types_or: [yaml, json]
